#os: linux
#dist: trusty
#sudo: required

language: java
jdk:
  - openjdk11
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2
  

branches:
  only:
    - /.*/
before_install:
  - sudo apt-get update

install: true
script: mvn clean package -DskipTests=true
  
jobs:
  include:  
    ## Build Stage  ##
    - stage: Build App
      if: branch = master
      script:
      - mvn clean package  -DskipTests=true

    ## Deploy Stage ##
    - stage: Deploy App
      if: branch = master
      script: 
      - mvn clean package   -DskipTests=true


notifications:
  email:
    on_failure: never
    on_success: never  
