## Server Properties
server:
    port: 8080
    servlet:
        session:
            cookie:
                secure: true
                http-only: true


#Spring Properties
spring:
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false

    application:
        name: SpringSecurity-Data-Application
    # Jpa Properties
    datasource:
        url: jdbc:mysql://bcmc.cy8obdina40j.us-east-1.rds.amazonaws.com:3306/spring_security_data?serverTimezone=UTC
        username: admin
        password: MIURsO1WJd2oNFin6jju
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        generate-ddl: true
        properties:
            hibernate:
                ddl-auto: update
                show_sql: false

                cache:
                    use_query_cache: true
                    use_second_level_cache: true
                    hazelcast:
                        use_native_client: true
                    region:
                        factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory

    # Spring Session properties
    session:
        jdbc:
            table-name: SPRING_SESSION
            initialize-schema: always
    devtools:
        restart:
            enabled: true

management:
    endpoints:
        web:
            exposure:
                include: ["health","info"]
    endpoint:
        auditevents:
            enabled: true
logging:
    level:
        org:
            springframework:
                web: DEBUG
