# Application Properties
spring:
  application:
    name: SpringSecurity-Data-Application
  # Jpa Properties
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: update

  # Spring Session properties
  session:
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
  devtools:
    restart:
      enabled: true

## Server Properties
server:
  port: ${server.port}
  servlet:
    session:
      cookie:
        secure: false
        http-only: true

management:
  endpoints:
    web:
      exposure:
        include: ["health","info"]
  endpoint:
    auditevents:
      enabled: true



