# Application Properties
spring:
  application:
    name: SpringSecurity-Data-Application
  # Jpa Properties
  datasource:
    #spring.datasource.url=jdbc:mysql://localhost:3306/springsecuritydb?useSSL=false
    url: jdbc:mysql://localhost:3306/spring_security_data?serverTimezone=UTC
    username: root
    password: bcmc1234
  jpa:
    hibernate:
      ddl-auto: none

  # Spring Session properties
  session:
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
  devtools:
    restart:
      enabled: true
  liquibase:
    contexts: dev
    change-log: classpath:db/db.changelog-master.xml

## Server Properties
server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true
        http-only: true

management:
  endpoints:
    web:
      exposure:
        include: ["health","info"]
  endpoint:
    auditevents:
      enabled: true

# Logging
logging:
  file: /Users/pjadda/ELK-Stack/logback/springsecuritydata.log

# Bucket4J properties
bucket4j:
  enabled: true

  filters:
    - cache-name: buckets
      url: /*
      metrics:
        tags:
          - key: IP
            expression: getRemoteAddr()
            types: REJECTED_COUNTER # for data privacy reasons the IP should only be collected on bucket rejections
          - key: USERNAME
            expression: "@bucket4jSecurityService.username() != null ? @bucket4jSecurityService.username() : 'anonymous'"
          - key: URL
            expression: request.getRequestURI()
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 10
              unit: seconds
